### ISSUE TITLE
support for Yasnippet

### ISSUE THREAD

**Issue by gour** [idleberg/node-atomizr#3]
Hello,

I'd like, if possible, to stay with Emacs editor while working on the web stuff, so consider it would be nice if Atomizr would have support for [Yasippet](https://github.com/joaotavora/yasnippet) templating system?

**Comment by idleberg** [comment]
Pre-release:

```sh
$ git clone https://github.com/idleberg/node-atomizr --branch typescript
$ cd node-atomizr
$ yarn install && yarn link
```

You should then be able to to specify `--target yasnippet`

**Comment by gour** [comment]
Thanks a lot for your work on it!!

I've tried to e.g. convert atom-snippets into sublime for [this](https://github.com/GBratsos/atom-zurb-foundation) and conversion via:

```
atomizr components.cson --target sublime
```

does produce:

```
$ ls -l components.*
-rw-r--r--. 1 gour gour 48465 Ruj 27 21:19 components.cson
-rw-r--r--. 1 gour gour 45674 Lis  1 09:06 components.sublime-completions
```

but with `yasnippet` target I get only:

```
# -*- mode: snippet -*-
# # name: No-Bullet list
# # key: no-bullets
# --
<ul class="no-bullets">
  <li>$0</li>
</ul>
```
iow. only the first snippet is created...

Tried with the 'scissors' example, but then I get:

```
$ atomizr no-bullet.sublime-snippet --target yasnippet
This doesn't seem to be a valid Sublime Text snippet file. Aborting.
/home/gour/repos/external/node-atomizr/lib/convert.js:123
        throw error;
        ^

TypeError: Cannot read property 'completions' of undefined
    at Object.write (/home/gour/repos/external/node-atomizr/lib/converter/yasnippet.js:5:14)
    at Object.sublime2yasnippet (/home/gour/repos/external/node-atomizr/lib/convert.js:120:28)
    at /home/gour/repos/external/node-atomizr/lib/convert.js:275:32
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
```

so, wonder what do I miss?

**Comment by idleberg** [comment]
> iow. only the first snippet is created...

This is expected behavious

> Tried with the 'scissors' example, but then I get:

Should be fixed in the `typescript` branch. Pull & try again.

This project deserves a full rewrite 😅

**Comment by gour** [comment]
> This project deserves a full rewrite sweat_smile

Do you still plan to make this working by rewrite?

**Comment by idleberg** [comment]
I actually started working on it, but the project doesn't have top priority

**Comment by gour** [comment]
@idleberg OK, I just want to tell you there are customers interested to use it - creating yasnippet for e.g.  Foundation. ;)

**Comment by idleberg** [comment]
> OK, I just want to tell you there are customers interested to use it - creating yasnippet for e.g. Foundation. ;)

See my post from October 1st

**Comment by gour** [comment]
I do attempt to convert Atom [package for Foundation](https://github.com/GBratsos/atom-zurb-foundation/tree/master/snippets), but I get the following:

```
$ atomizr  "*.cson" --target yasnippet
Writing "scss.sublime-completions"
Writing "typography.sublime-completions"
Writing "grid.sublime-completions"
Writing "components.sublime-completions"
Writing "templates.sublime-completions"
```

iow. why it does not write yasnippet format. What am I doing wrong?

**Comment by idleberg** [comment]
> OK, I just want to tell you there are customers interested to use it

**customer**
*ˈkʌstəmə*

noun
plural noun: customers

a person who **buys** goods or services from a shop or business

**Comment by gour** [comment]
> a person who buys goods or services from a shop or business

OK, it should be written as 'customers' to justify the meaning of:

"a person who 'buys' goods or services from a shop or business" alluding to the nature of open-source, but it looks the joke didn't go through well. ;)
