### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gour** [idleberg/node-atomizr#4]
Hello,

when attempting to convert VSCode (e.g. [this](https://github.com/dons20/UIKit-VSCode) one) snippets into something else I get the following:

```
$ atomizr javascript.json --target sublime
/usr/lib/node_modules/node-atomizr/index.js:17
            throw error;
            ^

TypeError: Cannot read property 'length' of undefined
    at Object.read_cson (/usr/lib/node_modules/node-atomizr/lib/atom.js:46:50)
    at Object.atom2sublime (/usr/lib/node_modules/node-atomizr/index.js:14:25)
    at fs.readFile.e (/usr/lib/node_modules/node-atomizr/bin/cmd.js:78:34)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

Any hint?

Maybe it's due to:

> When converting an existing Visual Studio Code snippet, the target scope for the target should be supplied (e.g. --scope .source.haskell)

but it's not clear what does it mean actually?

**Comment by idleberg** [comment]
>>When converting an existing Visual Studio Code snippet, the target scope for the target should be supplied (e.g. --scope .source.haskell)
>
>but it's not clear what does it mean actually?

Visual Studio Code stores the snippet's scope in `package.json`, not in the snippet file itself

**Comment by gour** [comment]
So if the `package.json` contains the following:

```
...
"categories": [
        "Snippets"
    ],
    "keywords": [
        "uikit",
        "html",
        "php",
        "twig",
        "javascript"
    ],
    "contributes": {
        "snippets": [
            {
                "language": "html",
                "path": "./snippets/snippets.json"
            },
...
```

what would be the correct invocation of `atomizr` ?

**Comment by idleberg** [comment]
I think you would need to pass `--scope text.html` (or `text.html.plain`, depending on how strict you need your snippets to be). However, I don't think the error in your initial post is related to this.

**Comment by gour** [comment]
> However, I don't think the error in your initial post is related to this.

You're right! The above workarounds do not help. :-(
